# Generated by Django 3.2.6 on 2021-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('trash', 'Trash'), ('inherit', 'Inherit'), ('auto-draft', 'Auto Draft')], max_length=20),
        ),
    ]
