# Generated by Django 3.2.6 on 2021-08-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
    ]
